name: Publish Docker

on:
  workflow_dispatch:

env:
  IMAGE: evcc/optimizer

jobs:
  publish:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ github.sha }}
            ${{ env.IMAGE }}:latest
